### ISSUE TITLE
Any interest in forking crossfilter and combining it with reductio?

### ISSUE THREAD

**Issue by jefffriesen** [esjewett/reductio#19]
@esjewett 
I know you're aware of this thread about keeping crossfilter moving forward: https://github.com/square/crossfilter/issues/151

Reductio follows the Node approach of small modules built on top of one another, which has it's benefits. But the functions you've built in reductio are so commonly needed that it's a good argument to include them in the crossfilter library itself. At the same time, Square isn't able to put more resources into Crossfilter, and it's been a slow process in opening it up to other contributors.

There was talk of crossfilter being part of dc.js, but I don't think that makes sense. I use it outside of dc.js.

One solution would be for you to just fork crossfilter and combine it with reductio. You could invite collaborators that are in that other thread. It could be moved into an official organization, but I don't know if that is necessary.

Getting something up and running and starting to address a couple of the biggest issues crossfilter has right now, such as support for more than 32 dimensions and web workers (https://github.com/square/crossfilter/issues/53) would be awesome and I think move the decision-making process along quicker. If it's done well, it will become the "blessed fork" and take some heat off the Square folks. 

I think you would be great to take this on because of what you've done so far with reductio. 

I'm asking in this repo instead of the other thread because you would be driving it initially (but I'm making sure to reference that thread so this question shows up there). Not sure if you like this approach and could take it on. If you do, I bet the other folks would support you in doing it. 

Just an idea...

**Comment by esjewett** [comment]
Hi @jefffriesen - thanks for the suggestion! I think I'd prefer to keep reductio as a somewhat independent wrapper of Crossfilter, but would love to see it get more popular :-)

On the topic of a Crossfilter fork, it seems it has been mostly decided to fork Crossfilter into its own independent project and we have a few people including me who have volunteered to help maintain it, merge pull requests, and (as time allows) push forward on those older nagging issues. Stand by for more on that please!

**Comment by jefffriesen** [comment]
Cool. Looking forward to it. Hope I can contribute as time permits.
