### ISSUE TITLE
Count Distinct

### ISSUE THREAD

**Issue by nordfjord** [esjewett/reductio#29]
Is there a way to count distinct values currently?

I have a creeping suspicion I will be needing to do some cardinality dimensions and having them as reducers would be awesome

```js
var group = reductio()
  .countDistinct(d => d.order_number)
  (group);
```

would have
```json
[{
  "key": "dimension1",
  "value": {
    "countDistinct": 4
  }
}, {
  "key": "dimension2",
  "value": {
    "countDistinct": 2
  }
}]
```

**Comment by nordfjord** [comment]
I will get on implementing this if there's no way to achieve this currently

**Comment by esjewett** [comment]
Exception aggregation is badly named, but is designed to handle this use-case: https://github.com/esjewett/reductio#aggregations-standard-aggregations-exception-aggregation

**Comment by nordfjord** [comment]
Awesome :+1:

**Comment by esjewett** [comment]
If you have any suggestions for naming it better, I'm all ears. I was thinking "unique" or "uniqueBy" - https://github.com/esjewett/reductio/blob/master/NOTES.md

**Comment by nordfjord** [comment]
I would've chosen "distinct", but that is mainly because it's standard SQL.

```SQL
SELECT DISTINCT CustomerName
FROM Customers
```

in SQL `unique` is used in the create table statement to indicate a field contains unique values.

**Comment by Fil** [comment]
agree with `distinct` (at least this is how I landed on this page: searching for "reductio count distinct") :-)
