### ISSUE TITLE
Consider NaN filtering

### ISSUE THREAD

**Issue by mr23** [esjewett/reductio#3]
I have some sparse data I would like to use with reductio/dc. I would prefer not to have to prefilter the data, and would like reductio to ignore/filter the NaN's. I have several cases where this would be helpful.

Please review the code changes at the following branch.
https://github.com/mr23/reductio/commit/130305f324ff6e8886fd0e9890f3d08f3ed64198

**Comment by esjewett** [comment]
Hopefully the just-published 0.2.0 with the filter capability from @Hauenstein addresses this issue!
