### ISSUE TITLE
max

### ISSUE THREAD

**Issue by ksknysn** [esjewett/reductio#33]
hi,
i don't use open soruce. i use windows and want to use just max values of some data. there are more than one values of data and i want to group by firstly department name and after daiyly and calculate max value day.
department                group                   day               count
--------------              ------------             ---------          ------------
computer                  software            27/2/2015       3
computer                 hardware            27/2/2015      2
electric                     left                      25/2/2014      3
computer                 technical             30/2/2015       4
is there any simple solution for this?

solution is:
computer     27/2/2015      5
electric        25/2/2015       3

**Comment by esjewett** [comment]
Closing - as mentioned in email, if using DC.js, can also use Reductio.
