### ISSUE TITLE
Do exceptions support multiple values

### ISSUE THREAD

**Issue by lbk3918** [esjewett/reductio#8]
Apologies if this is the wrong place to raise what is probably a question or a suggestion rather than an issue - does reductio.exception support multiple values in the same way as reductio.value - i.e. can I code reductio.value.exceptionsum for multiple items under the same reductio.exception unique key?

From my attempts I don't think this can be done via reductio, however I have a flattened one-to-many dataset where I have 2 separate values to sum at the lowest detail level, and 2 other separate values to sum at the exception level, so I need to do this either via reductio or using custom reduceAdd etc functions.

**Comment by esjewett** [comment]
Not sure I completely follow. You can theoretically have as many "values" as you want and defined an exceptionSum on each of them. I would expect that the following defines 2 independent exceptionSums at the 'bar' level and 2 normal sums (at the lowest detail level).

```javascript
var reducer = reductio();
reducer.value("w").exception(function(d) { return d.bar; }).exceptionSum(function(d) { return d.num1; });
reducer.value("x").exception(function(d) { return d.bar; }).exceptionSum(function(d) { return d.num2; });
reducer.value("y").sum(function(d) { return d.num3; });
reducer.value("z").sum(function(d) { return d.num4; });
reducer(group);
```

Should result in groups that look like

```javascript
{ key: barValue, value: {
  w: { exceptionSum: 2 },
  x: { exceptionSum: 3 },
  y: { sum: 4 },
  z: { sum: 2 }
}}
```

At least, that's how it's supposed to work. I'm only using this functionality in a couple of places in projects at the moment, so if it's not working properly, please let me know!

**Comment by esjewett** [comment]
Oh, and yes this is a fine place to raise questions and suggestions at the moment. If it starts to get out of hand, then I'll let people know, but there is not a lot of traffic here for now :)

**Comment by lbk3918** [comment]
Hi Ethan thanks for the example above, I had my values/exceptions syntax slightly wrong (not rare for me in javascript) and the errors raised led me to think this probably couldn't be done with reductio - I had in fact given up and was back to coding my own exception key/counts in my custom reduceAdd etc. functions.
When I read your reply I tried again with reductio and all is now working perfectly - what a great library, really saved me a lot of time & trouble, thanks again!

**Comment by esjewett** [comment]
Glad to hear it's working for you, and thank you for the kind words!
